version: "3.9"
services:
   db:
      image: postgres:latest
      restart: always
      ports:
         - 5432:5432
      environment:
         POSTGRES_USERNAME: postgres
         POSTGRES_PASSWORD: root
         POSTGRES_DATABASE: itelcdb
